project_id = "sjyozbaezibkerqoppor"

[functions.validate-address]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.places-details]
verify_jwt = false

[functions.static-map]
verify_jwt = true